apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels: 
        app: nodejs-app  
    spec:                 
      containers: 
      - name: nodejs-docker-demo 
        image: jdailama/nodejs-docker-demo:latest
        imagePullPolicy: Always
        ports:
        - name: nodejs-port
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: nodejs-app
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: nodejs-app
  type: LoadBalancer
